version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "4000:80"
    volumes:
      - .:/sampleapp
      - /sampleapp/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
